In [119]:
from sqlalchemy import create_engine, MetaData, Table
import pandas as pd
import geopandas as gpd
from datetime import datetime

USER_DB = 'postgres'
PASS_DB = 'A123456*'
HOST_DB = 'localhost'
PORT_DB = '5433'
NAME_DB = 'utea'

ENGINE = create_engine(f'postgresql+psycopg://{USER_DB}:{PASS_DB}@{HOST_DB}:{PORT_DB}/{NAME_DB}')

metadata = MetaData()
msj_whatsapp_tbl = Table("msj_whatsapp", metadata, autoload_with=ENGINE, schema="notificaciones_wsp")

In [120]:
PATH_XLSX_AVANCE_COSECHA = r'G:\Ingenio Azucarero Guabira S.A\UTEA - SEMANAL - AVANCE COSECHA\2025\AVANCE SEMANAL\AVANCE DE COSECHA V1.xlsx'
PATH_XLSX_CONTACTOS_GRUPOS = r'G:\Ingenio Azucarero Guabira S.A\UTEA - SEMANAL - AVANCE COSECHA\2025\DATA\CONTACTOS_GRUPO.xlsx'

In [121]:
df_avance_por_variedad = pd.read_excel(PATH_XLSX_AVANCE_COSECHA, sheet_name='AVANCE POR VARIEDADES')
df_contactos_grupos = pd.read_excel(PATH_XLSX_CONTACTOS_GRUPOS)

C:\Users\Usuario\anaconda3\envs\utea\lib\site-packages\openpyxl\worksheet\_reader.py:329: UserWarning: Unknown extension is not supported and will be removed
  warn(msg)
C:\Users\Usuario\anaconda3\envs\utea\lib\site-packages\openpyxl\worksheet\_reader.py:329: UserWarning: Conditional Formatting extension is not supported and will be removed
  warn(msg)

In [122]:
# coloca la fila 1 como cabecera
df_avance_por_variedad.columns = df_avance_por_variedad.iloc[1]
# descarta las primeras 2 filas, (fila en blanco y fila de nombres de caberas)
df_avance_por_variedad = df_avance_por_variedad.iloc[2:].reset_index(drop=True)
# elimina la ultima fila (Totales)
df_avance_por_variedad = df_avance_por_variedad.iloc[:-1]
# elimina las primeras 7 columnas
df_avance_por_variedad = df_avance_por_variedad.iloc[:, 7:].copy()
df_avance_por_variedad.head(5)

1,COD_COS,CAÑERO,COSECHADO,SIN COSECHA,SEMILLA,TOTAL AREA,%COSECHADO
0,173,AGROP. VICENTE ROCA GIL SRL,36.78,137.88,NaN,174.66,0.210581
1,7,NAZER PARADA ROBERTO DOMINGO,NaN,102.2,NaN,102.2,NaN
2,142,INSERVA DAMIANA S.R.L.,63.73,81.43,NaN,145.16,0.439033
3,33,AGROP. TRES HNOS DEL ORIENTE,147.74,70.41,NaN,218.15,0.67724
4,398,VARGAS PINTO RENNY EDWIN,107.14,55,NaN,162.14,0.660787

In [123]:
df_avance_por_variedad = df_avance_por_variedad[df_avance_por_variedad['SIN COSECHA'] > 10]
df_avance_por_variedad

1,COD_COS,CAÑERO,COSECHADO,SIN COSECHA,SEMILLA,TOTAL AREA,%COSECHADO
0,173,AGROP. VICENTE ROCA GIL SRL,36.78,137.88,NaN,174.66,0.210581
1,7,NAZER PARADA ROBERTO DOMINGO,NaN,102.2,NaN,102.2,NaN
2,142,INSERVA DAMIANA S.R.L.,63.73,81.43,NaN,145.16,0.439033
3,33,AGROP. TRES HNOS DEL ORIENTE,147.74,70.41,NaN,218.15,0.67724
4,398,VARGAS PINTO RENNY EDWIN,107.14,55,NaN,162.14,0.660787
5,6,FRERKING ORTIZ RICARDO,6.86,53.13,NaN,59.99,0.114352
6,393,AYALA ESPINOSA LEOPOLDO,56.76,51.88,NaN,108.64,0.522459
7,416,CIRBIAN LISSY F. COLAMARINO DE,15.73,49.93,NaN,65.66,0.239567
8,194,AGUILERA TARADELLES JOSE LUIS,7.48,45.29,NaN,52.77,0.141747
9,250,MORA MIRANDA WILLAN,79.85,43.27,NaN,123.12,0.648554
10,1,AGUILERA OLGA RIVERO VDA DE,103.6,34.84,NaN,138.44,0.748339
11,238,AGUILERA ANEZ JHONNY,13.22,25.5,NaN,38.72,0.341426
12,605,HURTADO PEREDO ANTONIO,NaN,22.24,NaN,22.24,NaN
13,198,AGUILERA TARRADELLES GUILLERMO,43.39,21.13,NaN,64.52,0.672505
14,76,DON SERAFIN SRL.,45.22,20.91,NaN,66.13,0.683805
15,179,PIL ANDINA S.A.,7.86,19.92,NaN,27.78,0.282937
16,209,FRITZER CUELLAR SAMIR EDUARDO,39.67,19.69,NaN,59.36,0.668295
17,501,PALICIO PEREZ CARREÑO ADRIANA NICOLE,NaN,19.12,NaN,19.12,NaN
18,52,GUTIERREZ TARRADELLES ALFREDO,34.95,17.12,NaN,52.07,0.671212
19,529,ALVAREZ SEJAS BISMARCK,NaN,16.59,NaN,16.59,NaN
20,138,ASUBY S.R.L.,54.06,15.71,NaN,69.77,0.774832
21,170,COLAMARINO DI SILVIO ANGELO,3.33,15.15,NaN,18.48,0.180195
22,99,SOTO ARCE OLIVAR,10.27,15.07,NaN,25.34,0.405288
23,195,"AGROPECUARIA ""FLAMBOYAN""",137.39,11.99,1.753082,151.133082,0.909066
24,125,MEDRANO NUNEZ REMBERTO,NaN,11.2,NaN,11.2,NaN
25,403,CRONENBOLD AGUILERA ROBERTO,100.69,11.14,0.861236,112.691236,0.893503
26,196,GUTIERREZ AGUILERA WIDEN GUILLER,NaN,11.02,NaN,11.02,NaN
27,48,TARRADELLES MARTINEZ DIETER JORGE,17.58,10.52,NaN,28.1,0.625623
28,17,ZALZER ANTELO LUIS JHONNY,NaN,10.34,NaN,10.34,NaN
29,220,AMURRIO TAPIA JAIME,NaN,10.22,NaN,10.22,NaN

In [124]:
df_contactos_grupos.head(3)

   COD_COS             NOMBRE       NUM  OBS
0        1    SERGIO AGUILERA  77000503  NaN
1        1   NICOLAS AGUILERA  75067427  NaN
2        5  JUAN MANUEL ROJAS  76607676  NaN

In [125]:
# JOIN por la columna "id"
df = pd.merge(df_contactos_grupos, df_avance_por_variedad, left_on="COD_COS", right_on="COD_COS", how="inner")
df.head(3)

,COD_COS,NOMBRE,NUM,OBS,CAÑERO,COSECHADO,SIN COSECHA,SEMILLA,TOTAL AREA,%COSECHADO
0,1,SERGIO AGUILERA,77000503,NaN,AGUILERA OLGA RIVERO VDA DE,103.6,34.84,NaN,138.44,0.748339
1,1,NICOLAS AGUILERA,75067427,NaN,AGUILERA OLGA RIVERO VDA DE,103.6,34.84,NaN,138.44,0.748339
2,6,KLAUS FRERKING,77049491,NaN,FRERKING ORTIZ RICARDO,6.86,53.13,NaN,59.99,0.114352

In [126]:
df['fecha_registro'] = datetime.now()
df['cod_canero'] = df['COD_COS']
df['nombre_canero'] = df['NOMBRE']
df['numero_cel'] = df['NUM']

df['mensaje'] = df.apply(lambda row: f"""👉 *Estimado productor, le escribimos desde UTEA por lo siguiente:*

Según el 📡*Monitoreo Satelital* del avance de cosecha 2025 se observa que aún tiene *{row['SIN COSECHA']:.2f} hectáreas de caña de la variedad CITTCA 8522* en campo pendientes para cosechar.

🌱 Le recomendamos priorizar la cosecha de esta variedad lo antes posible por ser una variedad de maduracion temprana, dejarla más tiempo en campo involucra porcentaje de encorchamiento elevado y *perdidas de peso de hasta un 15%*.

🙏 Agradecemos la recepción de este mensaje y su compromiso con el buen manejo de su cosecha. 💪 Estamos seguros de que seguir esta recomendación traerá mejores resultados para su producción. 🚜""", axis=1)


df['enviado'] = False
df['fecha_enviado'] = None
df['numero_contac'] = '591' + df['NUM'].astype(str) + '@s.whatsapp.net'

In [127]:
df = df[['fecha_registro', 'cod_canero', 'nombre_canero', 'numero_cel', 'mensaje', 'enviado', 'fecha_enviado', 'numero_contac']]
df

,fecha_registro,cod_canero,nombre_canero,numero_cel,mensaje,enviado,fecha_enviado,numero_contac
0,2025-09-18 15:50:33.445139,1,SERGIO AGUILERA,77000503,"👉 *Estimado productor, le escribimos desde UTE...",False,None,59177000503@s.whatsapp.net
1,2025-09-18 15:50:33.445139,1,NICOLAS AGUILERA,75067427,"👉 *Estimado productor, le escribimos desde UTE...",False,None,59175067427@s.whatsapp.net
2,2025-09-18 15:50:33.445139,6,KLAUS FRERKING,77049491,"👉 *Estimado productor, le escribimos desde UTE...",False,None,59177049491@s.whatsapp.net
3,2025-09-18 15:50:33.445139,7,DOMINGO NAZER,77624793,"👉 *Estimado productor, le escribimos desde UTE...",False,None,59177624793@s.whatsapp.net
4,2025-09-18 15:50:33.445139,17,ZALZER ANTELO LUIS JHONNY,77397105,"👉 *Estimado productor, le escribimos desde UTE...",False,None,59177397105@s.whatsapp.net
5,2025-09-18 15:50:33.445139,33,MILTON HACOB,76058151,"👉 *Estimado productor, le escribimos desde UTE...",False,None,59176058151@s.whatsapp.net
6,2025-09-18 15:50:33.445139,52,GUTIERREZ TARRADELLES ALFREDO,75003832,"👉 *Estimado productor, le escribimos desde UTE...",False,None,59175003832@s.whatsapp.net
7,2025-09-18 15:50:33.445139,76,ARMANDO ESPINOSA,78514100,"👉 *Estimado productor, le escribimos desde UTE...",False,None,59178514100@s.whatsapp.net
8,2025-09-18 15:50:33.445139,99,SOTO ARCE OLIVAR,67767105,"👉 *Estimado productor, le escribimos desde UTE...",False,None,59167767105@s.whatsapp.net
9,2025-09-18 15:50:33.445139,138,WILMER GUZMAN,78171001,"👉 *Estimado productor, le escribimos desde UTE...",False,None,59178171001@s.whatsapp.net
10,2025-09-18 15:50:33.445139,142,RICHAR CASTILLO,75009545,"👉 *Estimado productor, le escribimos desde UTE...",False,None,59175009545@s.whatsapp.net
11,2025-09-18 15:50:33.445139,170,COLAMARINO DI SILVIO ANGELO,76010101,"👉 *Estimado productor, le escribimos desde UTE...",False,None,59176010101@s.whatsapp.net
12,2025-09-18 15:50:33.445139,173,MARIA LAURA FISHER,77301990,"👉 *Estimado productor, le escribimos desde UTE...",False,None,59177301990@s.whatsapp.net
13,2025-09-18 15:50:33.445139,179,ROBERTO - PIL ANDINA,72207658,"👉 *Estimado productor, le escribimos desde UTE...",False,None,59172207658@s.whatsapp.net
14,2025-09-18 15:50:33.445139,194,JOSE LUIS AGUILERA,77010520,"👉 *Estimado productor, le escribimos desde UTE...",False,None,59177010520@s.whatsapp.net
15,2025-09-18 15:50:33.445139,194,DANIEL ALI - ENCARGADO,67759316,"👉 *Estimado productor, le escribimos desde UTE...",False,None,59167759316@s.whatsapp.net
16,2025-09-18 15:50:33.445139,195,DANIEL,75555646,"👉 *Estimado productor, le escribimos desde UTE...",False,None,59175555646@s.whatsapp.net
17,2025-09-18 15:50:33.445139,196,"JUAN, ENCARGADO",69111108,"👉 *Estimado productor, le escribimos desde UTE...",False,None,59169111108@s.whatsapp.net
18,2025-09-18 15:50:33.445139,196,WIDEN GUTIERREZ,69111101,"👉 *Estimado productor, le escribimos desde UTE...",False,None,59169111101@s.whatsapp.net
19,2025-09-18 15:50:33.445139,198,AGUILERA ORTIZ SANTIAGO GUILLERMO,77310506,"👉 *Estimado productor, le escribimos desde UTE...",False,None,59177310506@s.whatsapp.net
20,2025-09-18 15:50:33.445139,209,SAMIR,71332052,"👉 *Estimado productor, le escribimos desde UTE...",False,None,59171332052@s.whatsapp.net
21,2025-09-18 15:50:33.445139,238,AGUILERA ANEZ JHONNY,67875446,"👉 *Estimado productor, le escribimos desde UTE...",False,None,59167875446@s.whatsapp.net
22,2025-09-18 15:50:33.445139,250,WILLIAN MORA,74930428,"👉 *Estimado productor, le escribimos desde UTE...",False,None,59174930428@s.whatsapp.net
23,2025-09-18 15:50:33.445139,393,LEOPOLDO AYALA,67840458,"👉 *Estimado productor, le escribimos desde UTE...",False,None,59167840458@s.whatsapp.net
24,2025-09-18 15:50:33.445139,398,RENNY VARGAS,77340813,"👉 *Estimado productor, le escribimos desde UTE...",False,None,59177340813@s.whatsapp.net
25,2025-09-18 15:50:33.445139,403,ROBERTO CRONEMBOLD,76097197,"👉 *Estimado productor, le escribimos desde UTE...",False,None,59176097197@s.whatsapp.net
26,2025-09-18 15:50:33.445139,416,ROBERT CIRBIN,70874994,"👉 *Estimado productor, le escribimos desde UTE...",False,None,59170874994@s.whatsapp.net
27,2025-09-18 15:50:33.445139,501,PALICIO PEREZ CARREÑO ADRIANA NICOLE,78423141,"👉 *Estimado productor, le escribimos desde UTE...",False,None,59178423141@s.whatsapp.net
28,2025-09-18 15:50:33.445139,529,ALVAREZ SEJAS BISMARCK,67188780,"👉 *Estimado productor, le escribimos desde UTE...",False,None,59167188780@s.whatsapp.net
29,2025-09-18 15:50:33.445139,605,JULIO VACA,70951751,"👉 *Estimado productor, le escribimos desde UTE...",False,None,59170951751@s.whatsapp.net
30,2025-09-18 15:50:33.445139,48,TARRADELLES MARTINEZ DIETER JORGE,78188288,"👉 *Estimado productor, le escribimos desde UTE...",False,None,59178188288@s.whatsapp.net
31,2025-09-18 15:50:33.445139,48,ROQUE ANZOATEGUI - ENCARGADO DE DIETER TARRADE...,76641048,"👉 *Estimado productor, le escribimos desde UTE...",False,None,59176641048@s.whatsapp.net
32,2025-09-18 15:50:33.445139,220,LIDIA PORTILLO,76613825,"👉 *Estimado productor, le escribimos desde UTE...",False,None,59176613825@s.whatsapp.net

In [128]:
def crear_mensaje(datos):    
    try:
        with ENGINE.begin() as conn:
            conn.execute(msj_whatsapp_tbl.insert(), datos.to_dict(orient='records'))
        print("✅ Se ha actualizado ")
    except Exception as e:
        print("❌ Error al insertar en tabla MSJ WHASTAPP", e)
    #return df

In [129]:
crear_mensaje(df)

✅ Se ha actualizado