In [1]:
import pandas as pd

In [2]:
def rgb2hex(rgb):
    r = int(rgb.split(',')[0])
    g = int(rgb.split(',')[1])
    b = int(rgb.split(',')[2])
    
    return "#{:02x}{:02x}{:02x}".format(r,g,b)

print(rgb2hex('150, 21, 0'))

#961500

In [3]:
tabla = pd.read_excel('NAX2.xls')

In [4]:
tabla

             PRODUCTO                       Label   Valores             RGB
0          PRODUCCION              Nulo (0 tn/ha)  0.140997    (150, 21, 0)
1          PRODUCCION       Muy Bajo (< 20 tn/ha)  0.249415    (199, 15, 1)
2          PRODUCCION  Bajo Medio (20 a 30 tn/ha)  0.362002    (226, 97, 0)
3          PRODUCCION        Bajo (30 a 40 tn/ha)   0.46625   (255, 229, 0)
4          PRODUCCION       Medio (40 a 50 tn/ha)  0.562159   (237, 255, 1)
..                ...                         ...       ...             ...
65               NDWI                    Muy Alto     0.821   (232, 16, 20)
66  EVOLUCION HIDRICA     15 dias perdida de agua       NaN     (112, 6, 6)
67  EVOLUCION HIDRICA     10 dias perdida de agua       NaN  (255, 116, 30)
68  EVOLUCION HIDRICA      5 dias perdida de agua       NaN  (30, 255, 255)
69  EVOLUCION HIDRICA   Ganado o manteniendo agua       NaN   (29, 20, 249)

[70 rows x 4 columns]

In [5]:
tabla['RGB']=tabla['RGB'].map(lambda x:x.replace('(',''))
tabla['RGB']=tabla['RGB'].map(lambda x:x.replace(')',''))

In [6]:
tabla

             PRODUCTO                       Label   Valores           RGB
0          PRODUCCION              Nulo (0 tn/ha)  0.140997    150, 21, 0
1          PRODUCCION       Muy Bajo (< 20 tn/ha)  0.249415    199, 15, 1
2          PRODUCCION  Bajo Medio (20 a 30 tn/ha)  0.362002    226, 97, 0
3          PRODUCCION        Bajo (30 a 40 tn/ha)   0.46625   255, 229, 0
4          PRODUCCION       Medio (40 a 50 tn/ha)  0.562159   237, 255, 1
..                ...                         ...       ...           ...
65               NDWI                    Muy Alto     0.821   232, 16, 20
66  EVOLUCION HIDRICA     15 dias perdida de agua       NaN     112, 6, 6
67  EVOLUCION HIDRICA     10 dias perdida de agua       NaN  255, 116, 30
68  EVOLUCION HIDRICA      5 dias perdida de agua       NaN  30, 255, 255
69  EVOLUCION HIDRICA   Ganado o manteniendo agua       NaN   29, 20, 249

[70 rows x 4 columns]

In [7]:
tabla['hex'] = tabla['RGB'].map(rgb2hex)

In [8]:
tabla

,PRODUCTO,Label,Valores,RGB,hex
0,PRODUCCION,Nulo (0 tn/ha),0.140997,"150, 21, 0",#961500
1,PRODUCCION,Muy Bajo (< 20 tn/ha),0.249415,"199, 15, 1",#c70f01
2,PRODUCCION,Bajo Medio (20 a 30 tn/ha),0.362002,"226, 97, 0",#e26100
3,PRODUCCION,Bajo (30 a 40 tn/ha),0.46625,"255, 229, 0",#ffe500
4,PRODUCCION,Medio (40 a 50 tn/ha),0.562159,"237, 255, 1",#edff01
...,...,...,...,...,...
65,NDWI,Muy Alto,0.821,"232, 16, 20",#e81014
66,EVOLUCION HIDRICA,15 dias perdida de agua,NaN,"112, 6, 6",#700606
67,EVOLUCION HIDRICA,10 dias perdida de agua,NaN,"255, 116, 30",#ff741e
68,EVOLUCION HIDRICA,5 dias perdida de agua,NaN,"30, 255, 255",#1effff
69,EVOLUCION HIDRICA,Ganado o manteniendo agua,NaN,"29, 20, 249",#1d14f9

In [54]:
c = '<sld:ColorMapEntry color="' + '#000000' + '" opacity="1" quantity="' + '20' + '" label="' + '20' + '"/>'

In [9]:
tabla['codigo'] = tabla.apply(lambda row: '<sld:ColorMapEntry color="' + row.hex + '" opacity="1" quantity="' + str(row.Valores) + '" label="' + row.Label + '"/>', axis=1)

In [10]:
tabla

,PRODUCTO,Label,Valores,RGB,hex,codigo
0,PRODUCCION,Nulo (0 tn/ha),0.140997,"150, 21, 0",#961500,"<sld:ColorMapEntry color=""#961500"" opacity=""1""..."
1,PRODUCCION,Muy Bajo (< 20 tn/ha),0.249415,"199, 15, 1",#c70f01,"<sld:ColorMapEntry color=""#c70f01"" opacity=""1""..."
2,PRODUCCION,Bajo Medio (20 a 30 tn/ha),0.362002,"226, 97, 0",#e26100,"<sld:ColorMapEntry color=""#e26100"" opacity=""1""..."
3,PRODUCCION,Bajo (30 a 40 tn/ha),0.46625,"255, 229, 0",#ffe500,"<sld:ColorMapEntry color=""#ffe500"" opacity=""1""..."
4,PRODUCCION,Medio (40 a 50 tn/ha),0.562159,"237, 255, 1",#edff01,"<sld:ColorMapEntry color=""#edff01"" opacity=""1""..."
...,...,...,...,...,...,...
65,NDWI,Muy Alto,0.821,"232, 16, 20",#e81014,"<sld:ColorMapEntry color=""#e81014"" opacity=""1""..."
66,EVOLUCION HIDRICA,15 dias perdida de agua,NaN,"112, 6, 6",#700606,"<sld:ColorMapEntry color=""#700606"" opacity=""1""..."
67,EVOLUCION HIDRICA,10 dias perdida de agua,NaN,"255, 116, 30",#ff741e,"<sld:ColorMapEntry color=""#ff741e"" opacity=""1""..."
68,EVOLUCION HIDRICA,5 dias perdida de agua,NaN,"30, 255, 255",#1effff,"<sld:ColorMapEntry color=""#1effff"" opacity=""1""..."
69,EVOLUCION HIDRICA,Ganado o manteniendo agua,NaN,"29, 20, 249",#1d14f9,"<sld:ColorMapEntry color=""#1d14f9"" opacity=""1""..."

In [11]:
tabla.to_excel('resul.xlsx', index=False)