In [80]:
import os
import pandas as pd
from amigocloud import AmigoCloud

In [82]:
files = os.listdir(r'C:\Users\UTEA\OneDrive - Ingenio Azucarero Guabira S.A (2)\UTEA_2022\EVALUACION DE COSECHADORAS\informes\WORD - Copy')
files

['11171_EC_18-08-2022_QUIROZ SARAVIA TEODOCIA.docx',
 '11645_EC_29-08-2022_ROJAS MEDRANO JUAN.docx',
 '11852_EC_11-07-2022_ROCA GIL VICENTE.docx',
 '12478_EC_18-07-2022_SERRATE COLAMARINO HUGO.docx',
 '12725_EC_01-09-2022_SEJAS CLAURE SINFOROSA.docx',
 '13062_EC_04-08-2022_SOTO ARCE BACILIO.docx',
 '14760_EC_15-07-2022_VARGAS PINTO RENE.docx',
 '14769_EC_18-08-2022_VARGAS URIONA MARIO.docx',
 '1540_EC_29-08-2022_CALVI PADILLA MARIO.docx',
 '1580_EC_11-08-2022_CALLE DELGADO IVER.docx',
 '1648_EC_30-08-2022_CALVI PADILLA SERGIO.docx',
 '1672_EC_07-07-2022_CAMPBELL BALCAZAR ALAN.docx',
 '1741_EC_02-09-2022_CARO ALTAMIRANO ROSARIO.docx',
 '17691_EC_26-07-2022_GUZMAN MONTANO PEDRO WILMER.docx',
 '18027_EC_23-07-2022_AGUILERA TARRADELLES GUILLERMO.docx',
 '18027_EC_25-08-2022_AGUILERA TARRADELLES GUILLERMO.docx',
 '180_EC_15-08-2022_AMURRIO ALBARRACIN ELISEO.docx',
 '18191_EC_01-08-2022_BALCAZAR SOLETO MARIO.docx',
 '18356_EC_11-07-2022_CATALA HUBBAUER JORGE ALBERTO.docx',
 '18358_EC_06-07-2022_ROJAS AMELUNGE CARLOS.docx',
 '18358_EC_18-07-2022_ROJAS AMELUNGE CARLOS.docx',
 '2029_EC_19-07-2022_COLAMARINO DI SILVIO ANGELO.docx',
 '2220_EC_17-08-2022_CRUZ VARGAS TITO JHONNY.docx',
 '2220_EC_28-07-2022_CRUZ VARGAS TITO JHONNY.docx',
 '2315_EC_28-07-2022_CORDOVA OLGUIN JUAN CARLOS.docx',
 '2446_EC_02-09-2022_CORDOVA SEJAS ALCIDES.docx',
 '2446_EC_08-07-2022_CORDOVA SEJAS ALCIDES.docx',
 '2488_EC_30-08-2022_CASTILLO CHOQUE RICHARD LUIS.docx',
 '2816_EC_11-07-2022_DONOSO BLANCO ALBERTO.docx',
 '2899_EC_05-07-2022_EGUEZ ELHAGE JOSE EDUARDO.docx',
 '2899_EC_05-08-2022_EGUEZ ELHAGE JOSE EDUARDO.docx',
 '30035_EC_13-08-2022_GUTIERREZ AGUILERA WIDEN GUILLER.docx',
 '3334_EC_01-09-2022_ENRIQUEZ PAICHUCAMA ERWIN A.docx',
 '3334_EC_10-08-2022_ENRIQUEZ PAICHUCAMA ERWIN A..docx',
 '3334_EC_31-08-2022_ENRIQUEZ PAICHUCAMA ERWIN A.docx',
 '3378_EC_26-08-2022_ESCOBAR MORATO VICTOR HUGO.docx',
 '3378_EC_28-07-2022_ESCOBAR MORATO VICTOR HUGO.docx',
 '3400_EC_10-08-2022_ESPINOZA AGUILAR JAIME OMAR.docx',
 '3408_EC_13-07-2022_ESPINOZA TERRAZAS MIGUEL.docx',
 '3414_EC_04-08-2022_ESPINOZA TERRAZAS SERAFIN.docx',
 '3421_EC_04-08-2022_ESPINOZA HURTADO ARMANDO.docx',
 '3466_EC_13-07-2022_ESPINOZA MAIDA RICHARD.docx',
 '3474_EC_05-08-2022_EGUEZ FOIANINI GLOVERT ESTEBAN.docx',
 '40149_EC_11-08-2022_PAZ REA JOSE ERNESTO.docx',
 '40149_EC_28-07-2022_PAZ REA JOSE ERNESTO.docx',
 '4061_EC_21-07-2022_FRITZER PAZ ROMEL.docx',
 '41594_EC_05-07-2022_AGROPECUARIA CAMPO DULCE S.R.L..docx',
 '4171_EC_29-08-2022_FRITZER CUELLAR SAMIR EDUARDO.docx',
 '446_EC_16-08-2022_AGUILERA ANEZ JHONNY.docx',
 '446_EC_25-08-2022_AGUILERA ANEZ JHONNY.docx',
 '4604_EC_17-08-2022_GARCIA V. ALFREDO DAVID.docx',
 '4779_EC_29-07-2022_GUZMAN MONTANO JOHNNY.docx',
 '4839_EC_14-07-2022_GUTIERREZ TARRADELLES ALFREDO.docx',
 '4844_EC_19-07-2022_TARRADELLES MARTINEZ DIETER JORGE.docx',
 '4882_EC_29-07-2022_GUZMAN MONTANO WILSON.docx',
 '5011_EC_03-08-2022_FRANCO ARIAS GREGORIO.docx',
 '515_EC_08-07-2022_AGUILERA OLGA RIVERO DE.docx',
 '515_EC_26-07-2022_AGUILERA OLGA RIVERO DE.docx',
 '5387_EC_03-08-2022_HURTADO ORTIZ RONALD.docx',
 '5387_EC_12-07-2022_HURTADO ORTIZ RONALD.docx',
 '556_EC_02-08-2022_AYALA ESPINOSA WALDO SELUB.docx',
 '594_EC_01-08-2022_AGROPECUARIA FLAMBOYAN.docx',
 '6436_EC_02-08-2022_JIMENEZ PEDRAZA GUALBERTO.docx',
 '6436_EC_15-07-2022_JIMENEZ PEDRAZA GUALBERTO.docx',
 '692_EC_17-08-2022_AMURRIO TAPIA JAIME.docx',
 '696_EC_31-08-2022_ALMENDRAS MURIEL LUCIO.docx',
 '75_EC_02-09-2022_AGUILERA TARADELLES MARIANO.docx',
 '75_EC_20-07-2022_AGUILERA TARADELLES MARIANO.docx',
 '8014_EC_06-07-2022_NAZER PARADA ROBERTO DOMINGO.docx',
 '805_EC_13-08-2022_AGROP. TRES HNOS DEL ORIENTE.docx',
 '805_EC_20-07-2022_AGROP. TRES HNOS DEL ORIENTE.docx',
 '86_EC_01-09-2022_AGUILERA TARADELLES JOSE LUIS.docx',
 '86_EC_02-09-2022_AGUILERA TARADELLES JOSE LUIS.docx',
 '86_EC_21-07-2022_AGUILERA TARADELLES JOSE LUIS.docx',
 '8814_EC_18-07-2022_MURIALDO MENDEZ WALTER DANIEL.docx',
 '9278_EC_30-08-2022_NUNEZ MARTINEZ BRAULIO.docx',
 '9677_EC_14-07-2022_OVANDO JIMENEZ JAIRO ESTEVAN.docx']

In [83]:
# ELIMINA LA EXTENCION DE LOS NOMBRES DE LOS ARCHIVOS
f = list(map(lambda x : x[:-5], files))
f

['11171_EC_18-08-2022_QUIROZ SARAVIA TEODOCIA',
 '11645_EC_29-08-2022_ROJAS MEDRANO JUAN',
 '11852_EC_11-07-2022_ROCA GIL VICENTE',
 '12478_EC_18-07-2022_SERRATE COLAMARINO HUGO',
 '12725_EC_01-09-2022_SEJAS CLAURE SINFOROSA',
 '13062_EC_04-08-2022_SOTO ARCE BACILIO',
 '14760_EC_15-07-2022_VARGAS PINTO RENE',
 '14769_EC_18-08-2022_VARGAS URIONA MARIO',
 '1540_EC_29-08-2022_CALVI PADILLA MARIO',
 '1580_EC_11-08-2022_CALLE DELGADO IVER',
 '1648_EC_30-08-2022_CALVI PADILLA SERGIO',
 '1672_EC_07-07-2022_CAMPBELL BALCAZAR ALAN',
 '1741_EC_02-09-2022_CARO ALTAMIRANO ROSARIO',
 '17691_EC_26-07-2022_GUZMAN MONTANO PEDRO WILMER',
 '18027_EC_23-07-2022_AGUILERA TARRADELLES GUILLERMO',
 '18027_EC_25-08-2022_AGUILERA TARRADELLES GUILLERMO',
 '180_EC_15-08-2022_AMURRIO ALBARRACIN ELISEO',
 '18191_EC_01-08-2022_BALCAZAR SOLETO MARIO',
 '18356_EC_11-07-2022_CATALA HUBBAUER JORGE ALBERTO',
 '18358_EC_06-07-2022_ROJAS AMELUNGE CARLOS',
 '18358_EC_18-07-2022_ROJAS AMELUNGE CARLOS',
 '2029_EC_19-07-2022_COLAMARINO DI SILVIO ANGELO',
 '2220_EC_17-08-2022_CRUZ VARGAS TITO JHONNY',
 '2220_EC_28-07-2022_CRUZ VARGAS TITO JHONNY',
 '2315_EC_28-07-2022_CORDOVA OLGUIN JUAN CARLOS',
 '2446_EC_02-09-2022_CORDOVA SEJAS ALCIDES',
 '2446_EC_08-07-2022_CORDOVA SEJAS ALCIDES',
 '2488_EC_30-08-2022_CASTILLO CHOQUE RICHARD LUIS',
 '2816_EC_11-07-2022_DONOSO BLANCO ALBERTO',
 '2899_EC_05-07-2022_EGUEZ ELHAGE JOSE EDUARDO',
 '2899_EC_05-08-2022_EGUEZ ELHAGE JOSE EDUARDO',
 '30035_EC_13-08-2022_GUTIERREZ AGUILERA WIDEN GUILLER',
 '3334_EC_01-09-2022_ENRIQUEZ PAICHUCAMA ERWIN A',
 '3334_EC_10-08-2022_ENRIQUEZ PAICHUCAMA ERWIN A.',
 '3334_EC_31-08-2022_ENRIQUEZ PAICHUCAMA ERWIN A',
 '3378_EC_26-08-2022_ESCOBAR MORATO VICTOR HUGO',
 '3378_EC_28-07-2022_ESCOBAR MORATO VICTOR HUGO',
 '3400_EC_10-08-2022_ESPINOZA AGUILAR JAIME OMAR',
 '3408_EC_13-07-2022_ESPINOZA TERRAZAS MIGUEL',
 '3414_EC_04-08-2022_ESPINOZA TERRAZAS SERAFIN',
 '3421_EC_04-08-2022_ESPINOZA HURTADO ARMANDO',
 '3466_EC_13-07-2022_ESPINOZA MAIDA RICHARD',
 '3474_EC_05-08-2022_EGUEZ FOIANINI GLOVERT ESTEBAN',
 '40149_EC_11-08-2022_PAZ REA JOSE ERNESTO',
 '40149_EC_28-07-2022_PAZ REA JOSE ERNESTO',
 '4061_EC_21-07-2022_FRITZER PAZ ROMEL',
 '41594_EC_05-07-2022_AGROPECUARIA CAMPO DULCE S.R.L.',
 '4171_EC_29-08-2022_FRITZER CUELLAR SAMIR EDUARDO',
 '446_EC_16-08-2022_AGUILERA ANEZ JHONNY',
 '446_EC_25-08-2022_AGUILERA ANEZ JHONNY',
 '4604_EC_17-08-2022_GARCIA V. ALFREDO DAVID',
 '4779_EC_29-07-2022_GUZMAN MONTANO JOHNNY',
 '4839_EC_14-07-2022_GUTIERREZ TARRADELLES ALFREDO',
 '4844_EC_19-07-2022_TARRADELLES MARTINEZ DIETER JORGE',
 '4882_EC_29-07-2022_GUZMAN MONTANO WILSON',
 '5011_EC_03-08-2022_FRANCO ARIAS GREGORIO',
 '515_EC_08-07-2022_AGUILERA OLGA RIVERO DE',
 '515_EC_26-07-2022_AGUILERA OLGA RIVERO DE',
 '5387_EC_03-08-2022_HURTADO ORTIZ RONALD',
 '5387_EC_12-07-2022_HURTADO ORTIZ RONALD',
 '556_EC_02-08-2022_AYALA ESPINOSA WALDO SELUB',
 '594_EC_01-08-2022_AGROPECUARIA FLAMBOYAN',
 '6436_EC_02-08-2022_JIMENEZ PEDRAZA GUALBERTO',
 '6436_EC_15-07-2022_JIMENEZ PEDRAZA GUALBERTO',
 '692_EC_17-08-2022_AMURRIO TAPIA JAIME',
 '696_EC_31-08-2022_ALMENDRAS MURIEL LUCIO',
 '75_EC_02-09-2022_AGUILERA TARADELLES MARIANO',
 '75_EC_20-07-2022_AGUILERA TARADELLES MARIANO',
 '8014_EC_06-07-2022_NAZER PARADA ROBERTO DOMINGO',
 '805_EC_13-08-2022_AGROP. TRES HNOS DEL ORIENTE',
 '805_EC_20-07-2022_AGROP. TRES HNOS DEL ORIENTE',
 '86_EC_01-09-2022_AGUILERA TARADELLES JOSE LUIS',
 '86_EC_02-09-2022_AGUILERA TARADELLES JOSE LUIS',
 '86_EC_21-07-2022_AGUILERA TARADELLES JOSE LUIS',
 '8814_EC_18-07-2022_MURIALDO MENDEZ WALTER DANIEL',
 '9278_EC_30-08-2022_NUNEZ MARTINEZ BRAULIO',
 '9677_EC_14-07-2022_OVANDO JIMENEZ JAIRO ESTEVAN']

In [84]:
# CANTIDAD DE ARCHIVOSa
len(files)

77

In [85]:
pdfs = pd.DataFrame({'nom':f})
pdfs

                                                 nom
0        11171_EC_18-08-2022_QUIROZ SARAVIA TEODOCIA
1             11645_EC_29-08-2022_ROJAS MEDRANO JUAN
2               11852_EC_11-07-2022_ROCA GIL VICENTE
3        12478_EC_18-07-2022_SERRATE COLAMARINO HUGO
4         12725_EC_01-09-2022_SEJAS CLAURE SINFOROSA
..                                               ...
72    86_EC_02-09-2022_AGUILERA TARADELLES JOSE LUIS
73    86_EC_21-07-2022_AGUILERA TARADELLES JOSE LUIS
74  8814_EC_18-07-2022_MURIALDO MENDEZ WALTER DANIEL
75         9278_EC_30-08-2022_NUNEZ MARTINEZ BRAULIO
76   9677_EC_14-07-2022_OVANDO JIMENEZ JAIRO ESTEVAN

[77 rows x 1 columns]

In [86]:
# CONECCION A AMIGOCLOG
acceso = open('../utea_scripts/api_key/api.key','r')
api_token = acceso.readlines()[0]
acceso.close()

amigocloud = AmigoCloud(token=api_token)
amigocloud

In [87]:
query = {'query': 'select cast(id as varchar), split_part(canhero, \' / \', 1)|| \'_EC_\' || to_char(fecha_de_registro, \'DD-MM-YYYY\') || \'_\' || split_part(canhero, \' / \', 2) nom from dataset_296354'}
project = 'https://app.amigocloud.com/api/v1/projects/32082/sql'
cursor = amigocloud.get_cursor(project, query)
#data = select['data'][0]

In [88]:
lt = []
for registro in cursor:
    lt.append(registro)

In [89]:
df = pd.DataFrame(lt)
df

     id                                                nom
0    94             446_EC_09-09-2022_AGUILERA ANEZ JHONNY
1    95          1672_EC_09-09-2022_CAMPBELL BALCAZAR ALAN
2     4          18358_EC_18-07-2022_ROJAS AMELUNGE CARLOS
3    96          515_EC_10-09-2022_AGUILERA OLGA RIVERO DE
4    84         5307_EC_06-09-2022_HUANCA MENCHAQUE VICTOR
..   ..                                                ...
100  72    3334_EC_31-08-2022_ENRIQUEZ PAICHUCAMA ERWIN A.
101  10  4844_EC_19-07-2022_TARRADELLES MARTINEZ DIETER...
102  53        180_EC_15-08-2022_AMURRIO ALBARRACIN ELISEO
103  21   4839_EC_14-07-2022_GUTIERREZ TARRADELLES ALFREDO
104  46  3474_EC_05-08-2022_EGUEZ FOIANINI GLOVERT ESTEBAN

[105 rows x 2 columns]

In [90]:
res = pd.merge(pdfs, df, how = 'left', on = ['nom','nom'])

In [91]:
print(len(res))
res

77

                                                 nom  id
0        11171_EC_18-08-2022_QUIROZ SARAVIA TEODOCIA  60
1             11645_EC_29-08-2022_ROJAS MEDRANO JUAN  66
2               11852_EC_11-07-2022_ROCA GIL VICENTE  24
3        12478_EC_18-07-2022_SERRATE COLAMARINO HUGO   9
4         12725_EC_01-09-2022_SEJAS CLAURE SINFOROSA  74
..                                               ...  ..
72    86_EC_02-09-2022_AGUILERA TARADELLES JOSE LUIS  75
73    86_EC_21-07-2022_AGUILERA TARADELLES JOSE LUIS   8
74  8814_EC_18-07-2022_MURIALDO MENDEZ WALTER DANIEL   1
75         9278_EC_30-08-2022_NUNEZ MARTINEZ BRAULIO  69
76   9677_EC_14-07-2022_OVANDO JIMENEZ JAIRO ESTEVAN  23

[77 rows x 2 columns]

In [92]:
def new_name(row):
    data = row.split('_')
    return data[0] + '_EVC_' + data[2] + '_' + data[3] + '_' + data[4]

In [93]:
res['name_file'] = res.apply(lambda row: row.nom + '_' + str(row.id), axis=1)
res['name_file'] = res['name_file'].map(new_name)
res

,nom,id,name_file
0,11171_EC_18-08-2022_QUIROZ SARAVIA TEODOCIA,60,11171_EVC_18-08-2022_QUIROZ SARAVIA TEODOCIA_60
1,11645_EC_29-08-2022_ROJAS MEDRANO JUAN,66,11645_EVC_29-08-2022_ROJAS MEDRANO JUAN_66
2,11852_EC_11-07-2022_ROCA GIL VICENTE,24,11852_EVC_11-07-2022_ROCA GIL VICENTE_24
3,12478_EC_18-07-2022_SERRATE COLAMARINO HUGO,9,12478_EVC_18-07-2022_SERRATE COLAMARINO HUGO_9
4,12725_EC_01-09-2022_SEJAS CLAURE SINFOROSA,74,12725_EVC_01-09-2022_SEJAS CLAURE SINFOROSA_74
...,...,...,...
72,86_EC_02-09-2022_AGUILERA TARADELLES JOSE LUIS,75,86_EVC_02-09-2022_AGUILERA TARADELLES JOSE LUI...
73,86_EC_21-07-2022_AGUILERA TARADELLES JOSE LUIS,8,86_EVC_21-07-2022_AGUILERA TARADELLES JOSE LUIS_8
74,8814_EC_18-07-2022_MURIALDO MENDEZ WALTER DANIEL,1,8814_EVC_18-07-2022_MURIALDO MENDEZ WALTER DAN...
75,9278_EC_30-08-2022_NUNEZ MARTINEZ BRAULIO,69,9278_EVC_30-08-2022_NUNEZ MARTINEZ BRAULIO_69
76,9677_EC_14-07-2022_OVANDO JIMENEZ JAIRO ESTEVAN,23,9677_EVC_14-07-2022_OVANDO JIMENEZ JAIRO ESTEV...

In [94]:
for i in res.index:
    nom_1 = r'C:\Users\UTEA\OneDrive - Ingenio Azucarero Guabira S.A (2)\UTEA_2022\EVALUACION DE COSECHADORAS\informes\WORD - Copy\\' + res['nom'][i] + '.docx'
    nom_2 = r'C:\Users\UTEA\OneDrive - Ingenio Azucarero Guabira S.A (2)\UTEA_2022\EVALUACION DE COSECHADORAS\informes\WORD - Copy\\' + res['name_file'][i] + '.docx'
    os.rename(nom_1, nom_2)