In [4]:
import pandas as pd

In [1]:
# ruta de carpera donde estan las llaves
ruta = open('../ruta.txt')
ruta = ruta.readlines()[0]
ruta

'C:\\Documents\\OneDrive - Ingenio Azucarero Guabira S.A\\_DATOS_PYTHON'

In [5]:
path_xlsx = r'C:\Documents\OneDrive - Ingenio Azucarero Guabira S.A\UTEA_2024\CALIDAD DE SIEMBRA\DATOS\_LA ESTACADA - OLGUITA.xlsx'

In [6]:
df = pd.read_excel(path_xlsx)
df

,PROPIEDAD:,LA ESTACADA,Unnamed: 2,LOTE:,A5,Unnamed: 5,VARIEDAD:,UCG9020,Unnamed: 8,Unnamed: 9
0,FECHA:,2024-02-20 00:00:00,NaN,CLICLO:,HOJA,NaN,AREA:,15.75,EDAD:,09 MESES
1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,MUESTRA,TOTAL YEMAS,PERFORADAS,ENRAIZAMIENTO,BROTACION,MUERTA,TOTAL \nINVIABLE,%,TOTAL \nVIABLE,%
3,1,267,8,15,9,0,32,0.11985,235,0.88015
4,2,279,0,2,34,0,36,0.129032,243,0.870968
5,3,296,2,7,34,0,43,0.14527,253,0.85473
6,4,254,5,3,15,0,23,0.090551,231,0.909449
7,5,266,0,0,27,0,27,0.101504,239,0.898496
8,6,279,1,9,40,0,50,0.179211,229,0.820789
9,7,262,9,5,35,0,49,0.187023,213,0.812977
10,8,265,19,19,23,0,61,0.230189,204,0.769811
11,9,303,3,0,49,0,52,0.171617,251,0.828383
12,10,278,12,0,41,NaN,53,0.190647,225,0.809353
13,TOTAL:,2749,59,60,307,0,426,0.154965,2323,0.845035
14,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
15,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
16,NaN,TOTAL YEMAS:,2749,NaN,NaN,NaN,NaN,NaN,NaN,NaN
17,NaN,% PERFORADAS:,0.021462,NaN,NaN,NaN,NaN,NaN,NaN,NaN
18,NaN,% ENRAIZADAS:,0.021826,NaN,NaN,NaN,NaN,NaN,NaN,NaN
19,NaN,% BROTACION:,0.111677,NaN,NaN,NaN,NaN,NaN,NaN,NaN
20,NaN,% MUERTAS:,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN
21,NaN,% YEMAS INVIABLES:,0.154965,NaN,NaN,NaN,NaN,NaN,NaN,NaN
22,NaN,% YEMAS VIABLES:,0.845035,NaN,NaN,NaN,NaN,NaN,NaN,NaN